"""Export editable demo projects; no package installation or code downloads."""

import platform
import sys
from dataclasses import asdict
from importlib.resources import files
from pathlib import Path

import numpy as np

from . import FlyBrain, __version__, available_backends
from .demos import DodgeArena, PulseScore, make_demo, render_wav
from .session import replay, write_json
from .viewer import write_replay_html

TEMPLATES = {
    "dodge": "Environment feedback -> neural rates -> left/right steering",
    "tones": "Synthetic pulses -> neural rates -> original WAV sound",
}


def export_run(session, output, frames, *, environment_factory):
    """Verify before exporting; never overwrite an existing output directory."""
    if type(frames) is not int or not 1 <= frames <= 10000:
        raise ValueError("frames must be in 1..10000")
    # Bound the CLI/export helper, without limiting the underlying Session API.
    if frames * session.period_ms / session.brain.config.dt_ms > 1_000_000:
        raise ValueError("run exceeds one million neural ticks")
    output = Path(output)
    if output.exists() or output.is_symlink():
        raise FileExistsError(f"Output already exists: {output}; choose a new directory")
    recording = session.record(frames)
    replay(recording, environment_factory=environment_factory)
    output.mkdir(parents=True, exist_ok=False)
    write_json(output / "recording.json", recording)
    session.save(output / "session.json")
    write_replay_html(recording, output / "replay.html")
    if isinstance(session.environment, PulseScore):
        render_wav(recording, output / "tones.wav")
    return {"verified_replay": True, "frames": frames, "output": str(output.resolve())}


def create_project(destination, template="dodge", *, model="toy", download=False):
    """Generate a source project from trusted bundled templates and model recipes."""
    if template not in TEMPLATES:
        raise ValueError("unknown template")
    destination = Path(destination)
    if destination.exists() or destination.is_symlink():
        raise FileExistsError(f"Project already exists: {destination}; choose a new directory")
    session = make_demo(template, model=model, download=download)
    # Local model paths must remain usable when the generated app runs elsewhere.
    model_ref = str(Path(model).resolve()) if Path(model).is_file() else str(model)
    recipe = {
        "schema_version": 1,
        "template": template,
        "model": model_ref,
        "model_fingerprint": session.brain.model.fingerprint,
        "backend": "cpu",
        "config": asdict(session.brain.config),
        "period_ms": session.period_ms,
        "encoder": session.encoder.snapshot(),
        "readout": session.readout.snapshot(),
        "environment": session.environment.snapshot(),
    }
    source = files("flybrain").joinpath("data/demo_app.py.txt").read_text(encoding="utf-8")
    license_text = (
        files("flybrain").joinpath("data/project-license.txt").read_text(encoding="utf-8")
    )
    readme = f"""# My flybrain {template} demo

**No CUDA required.** Generated by flybrain-sdk {__version__}.

With the SDK already installed, run `python app.py --output runs/first`.
Run `python app.py --frames 50 --output runs/check` for a shorter check.
Every output path must be new, so previous recordings are preserved.

For a new environment: `python -m pip install -r requirements.txt`.
The requirement pins the public Git tag; it does not assume a PyPI release.
If generated from an unreleased checkout, keep using that checkout until its tag is published.

## Make it yours

1. Edit `recipe.json`: change `encoder.weights` to change feature-to-current gains.
2. Change `readout.channels` weights, bounds or `scale_hz` to change output mapping.
3. Edit `build_session()` in `app.py` to replace the environment, encoder or readout.
4. Run again to a new directory. Compare input, requested and applied control in `replay.html`.

The script records a Python run, verifies its full feedback replay, and exports an HTML
playback viewer and checkpoint. Tones also exports WAV. The viewer is a recording;
it does not rerun the brain. No learned behavior or musical understanding is claimed.

The real model is downloaded only with `python app.py --download --output runs/real`.
Generate a real-model project with `flybrain init my-real --template {template}
--model male-cns-escape-v1 --download` (one line). Its recipe contains matching neuron IDs.
Simply replacing the toy model name leaves incompatible input/output IDs; update the
recipe mappings and fingerprint together when choosing another model.

Input observations are current environment features. LIF dynamics, projections and
control mappings are engineering assumptions. The model fingerprint detects accidental
model changes; it is not a biological validation. Model references never execute code.

See ATTRIBUTION.md and LICENSE before sharing. Keep generated runs out of your source
repository unless you intend to publish the embedded model and observations.
Contribute templates: https://github.com/freeman-1984-coder/flybrain-sdk/blob/main/CONTRIBUTING.md
"""
    attribution = (
        "# Attribution\n\nTemplate code: flybrain-sdk contributors, MIT (see LICENSE).\n\n"
        + (
            "Model: toy-v1, an artificially designed circuit, not measured anatomy.\n"
            if session.brain.model.name == "toy-v1"
            else "Model: MaleCNS escape-v1, derived from MaleCNS v1.0, CC BY 4.0.\n"
            "Berg et al., Sexual dimorphism in the complete connectome of the Drosophila "
            "male central nervous system. FlyEM/HHMI Janelia, Cambridge and Google Research.\n"
            "Data: https://male-cns.janelia.org/\n"
            "License: https://creativecommons.org/licenses/by/4.0/\n"
            "Adaptation: selected LC4/LPLC2/GF subgraph, normalized weights and LIF dynamics.\n"
        )
        + "\nInput and action mappings are engineered. Tones are original synthesized audio.\n"
        + f"Model fingerprint: `{session.brain.model.fingerprint}`.\n"
    )
    destination.mkdir(parents=True, exist_ok=False)
    for name, content in {
        "app.py": source,
        "README.md": readme,
        "ATTRIBUTION.md": attribution,
        "LICENSE": license_text,
        "requirements.txt": (
            "flybrain-sdk @ git+https://github.com/freeman-1984-coder/"
            f"flybrain-sdk.git@v{__version__}\n"
        ),
        ".gitignore": "__pycache__/\n.venv/\nruns/\n",
    }.items():
        (destination / name).write_text(content, encoding="utf-8")
    write_json(destination / "recipe.json", recipe)
    return destination.resolve()


def doctor():
    """Read local capabilities and execute a small CPU smoke check; no network."""
    brain = FlyBrain.load("toy", backend="cpu")
    brain.stimulate("food", duration_ms=100)
    brain.advance(duration_ms=100)
    return {
        "sdk": __version__,
        "python": sys.version.split()[0],
        "numpy": np.__version__,
        "platform": platform.system(),
        "available_backends": available_backends(),
        "cpu_smoke": {"tick": brain.progress.tick, "action": brain.action().to_dict()},
        "network_used": False,
        "note": "Backend availability is not hardware conformance or a performance guarantee.",
    }


def run_preset(name, output, frames=300, *, model="toy", download=False):
    factory = DodgeArena.from_snapshot if name == "dodge" else PulseScore.from_snapshot
    session = make_demo(name, model=model, download=download)
    return export_run(session, output, frames, environment_factory=factory)
